fix #770 date keyword in Python >= 3.7
biocore/biom-format pull request #856
Opened 2021-05-04 07:56 UTC by schferbe

This is a revamp of #771 without adding external dependencies.

2021-05-04 18:38 UTC, wasade requested changes
Just some minor items, thanks!!

2021-05-04 18:38 UTC, wasade commented on ChangeLog.md
> +biom 2.1.11
```suggestion
biom 2.1.11-dev
```

2021-05-05 06:40 UTC, schferbe commented
I applied your suggestions. Thanks for the review!

2021-05-05 15:32 UTC, merged

2021-05-05 15:32 UTC, wasade commented
Thanks, @schferbe!